username: "12345678"
password: "testpassword_xxxxx"
public_key: "12345678:testpublickey_xxxxx"
sha_key: "xxxxx"
server: "https://api.lyra.com"
domain_url: "https://static.lyra.com"
currency: "EUR"
success_url: "/api/lyra/success"
notification_url: "/api/lyra/notification"